input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [level] == "ERROR" {
    mutate { add_tag => ["error"] }
  }

  mutate {
    rename => { "@timestamp" => "log_timestamp" }
  }

  date {
    match => ["log_timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "eduquest-logs-%{+YYYY.MM.dd}"
    action => "index"
  }
}
